Improve -Werror error messages:
Previously -Werror flags were causing a single error line like this:

  <no location info>: error:
  Failing due to -Werror.

With this patch we add source spans to -Werror lines, and also show which flag
made this warning an error. For example, when run with `-Werror=missing-fields
-Werror=incomplete-patterns`, we get

  test.hs:9:10: warning: [-Wincomplete-patterns]
      Pattern match(es) are non-exhaustive
      In a case alternative: Patterns not matched: (C2 _)
    |
  9 | sInt s = case s of
    |          ^^^^^^^^^...

  test.hs:9:10: error:
  Failing due to -Werror=incomplete-patterns
    |
  9 | sInt s = case s of
    |          ^^^^^^^^^...

  test.hs:12:14: warning: [-Wmissing-fields]
      • Fields of ‘Rec’ not initialised: f2
      • In the first argument of ‘print’, namely ‘Rec {f1 = 1}’
        In the expression: print Rec {f1 = 1}
        In an equation for ‘main’: main = print Rec {f1 = 1}
     |
  12 | main = print Rec{ f1 = 1 }
     |              ^^^^^^^^^^^^^

  test.hs:12:14: error:
  Failing due to -Werror=missing-fields
     |
  12 | main = print Rec{ f1 = 1 }
     |              ^^^^^^^^^^^^^